---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-system
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: cnpg-system
  targetNamespace: cnpg-system
  storageNamespace: cnpg-system
  upgrade:
    crds: CreateReplace
  values:
    monitoring:
      # -- Specifies whether the monitoring should be enabled. Requires Prometheus Operator CRDs.
      podMonitorEnabled: true
      # -- Metrics relabel configurations to apply to samples before ingestion.
      podMonitorMetricRelabelings: []
      # -- Relabel configurations to apply to samples before scraping.
      podMonitorRelabelings: []
      # -- Additional labels for the podMonitor
      podMonitorAdditionalLabels: {}
    
      grafanaDashboard:
        create: true
        # -- Allows overriding the namespace where the ConfigMap will be created, defaulting to the same one as the Release.
        namespace: "kube-prometheus-stack"
        # -- The name of the ConfigMap containing the dashboard.
        configMapName: "cnpg-grafana-dashboard"
        # -- Label that ConfigMaps should have to be loaded as dashboards.  DEPRECATED: Use labels instead.
        sidecarLabel: "grafana_dashboard"
        # -- Label value that ConfigMaps should have to be loaded as dashboards.  DEPRECATED: Use labels instead.
        sidecarLabelValue: "1"
        # -- Labels that ConfigMaps should have to get configured in Grafana.
        labels: {}
        # -- Annotations that ConfigMaps can have to get configured in Grafana.
        annotations: {}  
