---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 1h0m0s
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prometheus-stack
  storageNamespace: kube-prometheus-stack
  values:
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
