apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-nerdearla
  namespace: flux-system
spec:
  interval: 1m
  timeout: 15m
  targetNamespace: app-nerdearla
  storageNamespace: app-nerdearla
  releaseName: app-nerdearla
  chart:
    spec:
      chart: app-nerdearla/.helm/
      sourceRef:
        kind: GitRepository
        name: app-nerdearla
      valuesFiles:
        - app-nerdearla/.helm/values.yaml
      reconcileStrategy: Revision
